### ISSUE TITLE
Extension improvements

### ISSUE THREAD

**Issue by nomego** [rkraneis/brightness-rene.kraneis.gmail.com#1]
Hi!

Thanks for a great extension!
Brightness control through GNOME Settings doesn't work for me so I've been using xrandr to set it through CLI until I found your extension. But I didn't find it through extensions.gnome.org so you should post it there!

`xrandr | grep " connected" | cut -f 1 -d ' '` will produce a list of active outputs, so it would be nice if the extensions used that list to run the xrandr command on, would work with multi display.
Bonus to allow a selection of these in extension prefs ?

Scrolling on the icon to adjust brightness would also be nice, could maybe allow for more fine tuning instead of only presets?
https://gitorious.org/gnome-shell-brightness-extension/gnome-shell-brightness-extension?p=gnome-shell-brightness-extension:gnome-shell-brightness-extension.git;a=blob;f=brightness_control@lmedinas.org/extension.js;h=5e1eaf1460a0a7f7ce09496c2464705fb419d899;hb=HEAD for inspiration

Update to version 3.24!

**Comment by rkraneis** [comment]
Hi @nomego,
thank you for your comment. I myself recently switched to https://extensions.gnome.org/extension/1222/oled-dimmer/ as I am using wayland nowadays. I could nonetheless incorporate some of your suggestions, if this does not work for you.

**Comment by nomego** [comment]
Well I hard-coded my outputs as well so it will work for me, although the scrolling would have been nice.
Wayland on this machine is not 100% yet but maybe I should give it some more testing.
Thanks for the response!
